[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
utility_staking = "GmMTWPSwxFaM2Vsjpti6yCdx5akC2KCsiJ9jdEyAejLJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
